/*this is automatically generated by the vue create command. Probs wont have to change it
Vue uses this to inject our Vue components into the index.html

*/
import Vue from 'vue'   //access the vue stuff 
import App from './App.vue' //access the app.vue component 

Vue.config.productionTip = false

new Vue({  //instantiate a Vue application object 
  render: h => h(App), //render tells what the main component is called - must match name of an import
}).$mount('#app') //$mount- tells Vue where in teh index.html the vue components should be added
                  //#app - the element with id='app will have the vue components added to it