--
-- Show any actors we have in the actor table who are not in any films
-- in the film table (ie. no entry in the film_actor table)
--we want the difference between the entries in actor and film actor
--to get the difference we can use a subquery or an left-join. 


--
-- 1. Add some test data to the actor table we know are do not
--    have matches in the film table;
  -- since actor_id is generated by DB Manager we do not specify it in the insert
  -- the actor_id assigned may be different if the SQL on different DB Mangagers
  -- 
Begin transaction;
insert into actor (first_name, last_name) values('Anne', 'Joel');
insert into actor (first_name, last_name) values('Daniel', 'Louis');
insert into actor (first_name, last_name) values('Brianna', 'Hema');
insert into actor (first_name, last_name) values('Aidan', 'Patrick');
insert into actor (first_name, last_name) values('David', 'Connor');
insert into actor (first_name, last_name) values('Sam', 'Michael');
insert into actor (first_name, last_name) values('Luke', 'Sammi');
insert into actor (first_name, last_name) values('Jeff', 'Eric');
insert into actor (first_name, last_name) values('D. Avery', 'Danny');
insert into actor (first_name, last_name) values('Jason', 'Frank');

--
--  2a. Problem solved with NOT IN sub-query
--

select actor_id, count(*)
from actor
where actor_id not in (Select actor_id from film_actor) --give me actors who actpr_id is not in the list of actor_id in film
group by actor_id
;

--
-- Problem solved with left-join actor table to file_actor table
--

select a.actor_id, a.first_name, a.last_name
from actor a       --assign a correlation name (nick name) to the table for ease of coding
   left join      --show difference btween the rows in the first table and the second
   film_actor fa  --based on the actor_id
on a.actor_id = fa.actor_id
where fa.actor_id is null
;
--
-- 3. Reset table to original state before test data inserted
--
rollback;