package com.techelevator;

public class IntroToClassesCard {
        //------------------------------------------------------------------------------------------------------------
        // Application program for the Intro To Classes App
        //------------------------------------------------------------------------------------------------------------
        public static void main(String[] args) {
        /*
        *  This program will demonstrate several concepts presented in the Java cohort
        *  in the topic Introduction to Classes 		
        */
       //ClassName objName = new ClassName();  //if no constructor is not found then it runs of default. We need one.
	    PlayingCard aCard = new PlayingCard(); //we instantiated a PlayingCard object
	    System.out.println(aCard); //
	    
	    PlayingCard anotherCard = new PlayingCard(1, "Black", "Clubs");
	    System.out.println("anotherCard is: " + anotherCard);
	    
	    PlayingCard card3 = new PlayingCard(9, "Red", "Hearts");
	    System.out.println("card3 is: " + card3);
	    
	    card3.setCardValue(1);
	    System.out.println("The value is card3 is: " + card3.getCardValue());
        }
}
   
		 

       //getters and setters generated by eclipse follow the convention for getter and setter names
      //getVariableName   setVariableName isVariableName (boolean) Want conventional names!!